query getUserPerson($id: Int!) {
  User (id: $id) {
    id
    name
    avatar {
      large
    }
    bannerImage
  }
}

query getUserFollowing($id: Int!, $page: Int) {
  Page(page: $page) {
    pageInfo {
      total
      currentPage
      hasNextPage
    }
    following(userId: $id) {
      id
    }
  }
}

query getUserFollowers($id: Int!, $page: Int) {
  Page(page: $page) {
    pageInfo {
      total
      currentPage
      hasNextPage
    }
    followers(userId: $id) {
      id
    }
  }
}

query getUserOutbox($id: Int!, $page: Int) {
  Page(page: $page) {
    pageInfo {
      total
      currentPage
      lastPage
      hasNextPage
    }
    activities(
      userId: $id,
      sort: ID_DESC
    ) {
      __typename
      ... on TextActivity {
        id
        siteUrl
        createdAt
      }
      ... on ListActivity {
        id
        siteUrl
        createdAt
      }
      ... on MessageActivity {
        id
        siteUrl
        createdAt
      }
    }
  }
}
